version: "3.1"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  user_team_db:
      build: ./database/sql/.
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpass
        MYSQL_DATABASE: user_device_db
  elasticsearch:
    build:
      context: ./database/elasticSearch
      dockerfile: .
    ports:
      - "9201:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    tty: true
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  active_monitor:
    build:
      context: ./src/saveIdent.com
      dockerfile: activeMonitorService.dockerfile
    ports:
      - "1992:1992"
    depends_on:
      - redis
      - elasticsearch
      - user_team_db
  input_service:
    build:
      context: ./src/saveIdent.com
      dockerfile: input.dockerfile
    ports:
      - "1990:1990"
    depends_on:
      - redis
      - elasticsearch
      - user_team_db
  sql_service:
    build:
      context: ./src/saveIdent.com
      dockerfile: sqlService.dockerfile
    ports:
      - "1991:1991"
    depends_on:
      - redis
      - elasticsearch
      - user_team_db
  analytics:
    build:
      context: ./saveIdent-cluster/.
      dockerfile: .
    ports:
      - "1993:1993"
    depends_on:
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: .
    ports:
      - "8080:8080"
    depends_on:
      - analytics
      - sql_service
      - input_service
      - active_monitor