version: '3.1'

services:
  user_team_db:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpass
      MYSQL_DATABASE: user_device_db