version: "3.3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  user_team_db:
      build: ./database/sql/.
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpass
        MYSQL_DATABASE: user_device_db
  elasticSearch:
    image: